run_name: null
training:
  lr: 0.005
  restore_ckpt: null
  num_epochs: 5
  loss_fn: "crossentropy"
  batch_size: 64
  optimizer: "adam"
test:
  ckpt: null
logging: # frequency in number of iterations
  log_freq: 5
  val_freq: 2000
  save_freq: 2000
  ckpt_dir: "./ckpts"
inference:
  output_file: "predictions.json"
  gt_json: null 
  checkpoint: null 
  ngram: null 
model: # Any model parameters
  z_dim: 128